ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

--계정만들기
CREATE USER community_pja IDENTIFIED BY community1234;
ALTER USER community_pja DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

GRANT CONNECT,RESOURCE,CREATE VIEW TO community_pja;