SELECT DEPARTMENT_NAME "학과 명",CATEGORY "계열"
FROM tb_department;

SELECT DEPARTMENT_NAME || '의 정원은'||CAPACITY||'명 입니다.' AS "학과별 정원"
FROM tb_department;

SELECT STUDENT_NAME,department_name FROM TB_STUDENT
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE absence_yn = 'Y'
AND SUBSTR(STUDENT_SSN,8,1)=2
AND department_name = '국어국문학과';

SELECT STUDENT_NAME FROM TB_STUDENT
WHERE STUDENT_NO IN ( 'A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NO DESC;


SELECT DEPARTMENT_NAME,CATEGORY FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

SELECT PROFESSOR_NAME FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

SELECT CLASS_NO FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

SELECT DISTINCT CATEGORY FROM TB_DEPARTMENT;

SELECT STUDENT_NO,STUDENT_NAME,STUDENT_SSN FROM TB_STUDENT
WHERE ABSENCE_YN = 'N'
AND STUDENT_NO LIKE 'A2%'
AND STUDENT_ADDRESS LIKE '%전주%'
ORDER BY STUDENT_NAME;

-------------------------------------------------------------------------------------
--1
SELECT STUDENT_NO 학번,STUDENT_NAME 이름,ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO =02 
ORDER BY ENTRANCE_DATE;

--2
SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

--3
--SELECT PROFESSOR_NAME 교수이름 ,PROFESSOR_SSN 나이 
--FROM TB_PROFESSOR
--WHERE(SYSDATE-PROFESSOR_SSN+1);

       --ORA-01843: 지정한 월이 부적합합니다. '19'||안쓰면 오류 발생(주민등록상의 950103이라고 쓰여있어서 YY가 형태가 없다. YYYYMMDD)

SELECT PROFESSOR_NAME"교수이름"
FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE(19||SUBSTR(PROFESSOR_SSN,1,6),'YYYYMMDD'))//12)"나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1)=1
ORDER BY "나이";

--4
SELECT SUBSTR(PROFESSOR_NAME,2,2) 이름 
FROM TB_PROFESSOR;

--5
SELECT STUDENT_NO, STUDENT_NAME FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)
    -  EXTRACT(YEAR FROM  TO_DATE('19'||SUBSTR(STUDENT_SSN,1,6),'YYYYMMDD'))>19;
--WHERE SUBSTR(ENTRANCE_DATE,1,2) - SUBSTR(STUDENT_SSN,1,2) >=19;

--6
SELECT TO_CHAR((TO_DATE(20201225)), 'day')FROM DUAL;

--7
SELECT TO_DATE('99/10/11', 'YY/MM/DD') FROM DUAL;
SELECT TO_DATE('49/10/11', 'YY/MM/DD') FROM DUAL; 
SELECT TO_DATE('99/10/11', 'RR/MM/DD') FROM DUAL; 
SELECT TO_DATE('49/10/11', 'RR/MM/DD') FROM DUAL; 

--8
SELECT STUDENT_NO,STUDENT_NAME FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';

--12
SELECT SUBSTR(TERM_NO,1,4) AS "년도",ROUND(AVG(POINT),1) AS "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO='A112113'
GROUP BY  SUBSTR(TERM_NO,1,4)
ORDER BY 1;

--13                                         COUNT(함수식) - 함수의 결과가 있을떄 (NULL이 아닐때 카운트)-없는 칼럼을 만든다.        
SELECT DEPARTMENT_NO,COUNT(DECODE(ABSENCE_YN,'Y','Y','N0',0)) "휴학생 수 "
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

SELECT DEPARTMENT_NO,SUM(DECODE(ABSENCE_YN,'Y',1,0)) "휴학생 수 "
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--14
SELECT STUDENT_NAME 동일이름,COUNT(*) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*)>1
ORDER BY 1;


--15
-------------------------------------------------------------------------------------

--1
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지 
FROM TB_STUDENT ORDER BY STUDENT_NAME;

--2
SELECT STUDENT_NAME, STUDENT_SSN FROM TB_STUDENT 
WHERE ABSENCE_YN = 'Y' ORDER BY STUDENT_SSN DESC;

--3
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS "거주지 주소" 
FROM TB_STUDENT WHERE STUDENT_NO LIKE '9%' 
AND STUDENT_ADDRESS LIKE '%경기도%' OR STUDENT_ADDRESS LIKE '%강원도%'
ORDER BY STUDENT_NAME;

--4
SELECT PROFESSOR_NAME, PROFESSOR_SSN FROM TB_PROFESSOR 
WHERE DEPARTMENT_NO = '005' ORDER BY PROFESSOR_SSN;

--5
SELECT STUDENT_NO, TO_CHAR(POINT, '9.00') POINT FROM TB_GRADE 
WHERE TERM_NO = '200402' AND CLASS_NO = 'C3118100' 
ORDER BY POINT DESC, STUDENT_NO;

--6
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) ORDER BY STUDENT_NAME;

--7
SELECT CLASS_NAME, DEPARTMENT_NAME FROM TB_CLASS 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

--8
SELECT CLASS_NAME, PROFESSOR_NAME FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO);

--9
SELECT CLASS_NAME, PROFESSOR_NAME FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR P USING(PROFESSOR_NO) 
JOIN TB_DEPARTMENT D ON(P.DEPARTMENT_NO = D.DEPARTMENT_NO)  
WHERE CATEGORY = '인문사회';

--10
SELECT STUDENT_NO 학번, STUDENT_NAME "학생 이름", ROUND(AVG(POINT),1)"전체 평점" FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO) 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
WHERE DEPARTMENT_NAME = '음악학과' 
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY STUDENT_NO;

-- 11
SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, 
PROFESSOR_NAME 지도교수이름 FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

--12
SELECT STUDENT_NAME, TERM_NO TERM_NAME FROM TB_STUDENT 
JOIN TB_GRADE USING(STUDENT_NO) 
JOIN TB_CLASS USING(CLASS_NO) 
WHERE TERM_NO LIKE '2007%' AND CLASS_NAME = '인간관계론';

--13
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름", 
ROUND(AVG(POINT), 8) 평점 FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N' 
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME 
HAVING ROUND(AVG(POINT), 8) >=4.0  ORDER BY STUDENT_NO;

--14
SELECT STUDENT_NAME 학생이름, 
NVL(PROFESSOR_NAME, '지도교수 미지정') 지도교수 FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
LEFT JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO) 
WHERE DEPARTMENT_NAME = '서반아어학과' 
ORDER BY STUDENT_NO;

--15
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름", 
ROUND(AVG(POINT), 8) 평점 FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N' 
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME 
ORDER BY STUDENT_NO;

--16
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름", 
ROUND(AVG(POINT), 8) 평점 FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N' 
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME 
HAVING ROUND(AVG(POINT), 8) >= 4.0 ORDER BY STUDENT_NO;


--17
SELECT STUDENT_NAME, STUDENT_ADDRESS FROM TB_STUDENT 
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_STUDENT
WHERE STUDENT_NAME = '최경희');

--18 질문 
-- 국어 국문학과에서 총 평점이 가장 높은 학생의 이름과 학번을 표시하는 sql문을 작성하시오.
SELECT STUDENT_NO, STUDENT_NAME
FROM (SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT) 평점
      FROM TB_GRADE
      JOIN TB_STUDENT USING(STUDENT_NO)
      WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME ='국어국문학과')
      GROUP BY STUDENT_NO, STUDENT_NAME
      ORDER BY 평점 DESC)
WHERE ROWNUM = 1;
      
      
SELECT STUDENT_NO, STUDENT_NAME      
WHERE STUDENT_NO, STUDENT_NAME = (SELECT 
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
    JOIN TB_GRADE USING(STUDENT_NO) 
    WHERE DEPARTMENT_NAME = '국어국문학과' 
    GROUP BY STUDENT_NO, STUDENT_NAME 
    ORDER BY AVG(POINT) DESC)
WHERE ROWNUM = 1;
    
-- 19

